##################################
# BATTLE ROYALE HD PLUGIN CONFIG #
##################################

### phase settings ###
mining_border_diameter: 500
mining_phase_time: 30
fight_border_diameter: 100
fight_phase_time: 15
overtime_border_diameter: 20
overtime_phase_time: 5

### spawn default settings ###
spawn_x: 0.0
spawn_y: 100.0
spawn_z: 0.0
spawn_world: world

### bossbar settings ###
bossbar_enable: true
phase_color_mining: BLUE
phase_color_fight: RED
phase_color_overtime: PURPLE

# how long players are invisible after game start
invisibility_time: 5

### quick death settings ###
# what happens when overtime ends with multiple survivors
# options: lava, arrows, damage_dealt, box, hunger, random, none
quick_death: random
